using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class DIALOGUE : MonoBehaviour
{
    public GameObject Message;
    public Text SignText;
    public string messageTexte;

    private void Start()
    {
        Message.SetActive(false);
    }


    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            SignText.text = messageTexte;
            Message.SetActive(true);
        }
    }

    private void OnTriggerExit2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            Message.SetActive(false);
        }
    }
}